#!/bin/zsh

echo "## Environment"
echo ""
echo "- macOS: $(sw_vers -productVersion)"
echo "- Chip: $(uname -m)"
echo "- Shell: $SHELL"
[[ -x /opt/homebrew/bin/brew ]] && echo "- Homebrew: $(/opt/homebrew/bin/brew --version | head -1 | awk '{print $2}')"

echo ""
echo "## Languages & Runtimes"
echo ""
command -v python3 &>/dev/null && echo "- Python: $(python3 --version 2>&1 | awk '{print $2}')"
command -v node &>/dev/null && echo "- Node: $(node --version | tr -d 'v')"
command -v php &>/dev/null && echo "- PHP: $(php --version | head -1 | awk '{print $2}')"
command -v ruby &>/dev/null && echo "- Ruby: $(ruby --version | awk '{print $2}')"
command -v go &>/dev/null && echo "- Go: $(go version | awk '{print $3}' | tr -d 'go')"
command -v rustc &>/dev/null && echo "- Rust: $(rustc --version | awk '{print $2}')"
command -v java &>/dev/null && echo "- Java: $(java --version 2>&1 | head -1 | awk '{print $2}')"

echo ""
echo "## Tools"
echo ""
command -v git &>/dev/null && echo "- Git: $(git --version | awk '{print $3}')"
command -v docker &>/dev/null && echo "- Docker: $(docker --version 2>/dev/null | awk '{print $3}' | tr -d ',')"
command -v code &>/dev/null && echo "- VS Code: installed"
command -v cursor &>/dev/null && echo "- Cursor: installed"
command -v vim &>/dev/null && echo "- Vim: $(vim --version | head -1 | awk '{print $5}')"
command -v nvim &>/dev/null && echo "- Neovim: $(nvim --version | head -1 | awk '{print $2}')"
command -v tmux &>/dev/null && echo "- tmux: $(tmux -V | awk '{print $2}')"

echo ""
echo "## Package Managers"
echo ""
command -v pip3 &>/dev/null && echo "- pip: $(pip3 --version 2>&1 | awk '{print $2}')"
command -v npm &>/dev/null && echo "- npm: $(npm --version)"
command -v yarn &>/dev/null && echo "- yarn: $(yarn --version 2>/dev/null)"
command -v pnpm &>/dev/null && echo "- pnpm: $(pnpm --version 2>/dev/null)"
command -v composer &>/dev/null && echo "- Composer: $(composer --version 2>/dev/null | awk '{print $3}')"
command -v cargo &>/dev/null && echo "- Cargo: $(cargo --version | awk '{print $2}')"

# Python version management
[[ -d "$HOME/.pyenv" ]] && echo "- pyenv: installed"
command -v conda &>/dev/null && echo "- conda: $(conda --version | awk '{print $2}')"

# Node version management  
[[ -d "$HOME/.nvm" ]] && echo "- nvm: installed"
command -v fnm &>/dev/null && echo "- fnm: installed"

echo ""
echo "## Databases & Services"
echo ""
command -v mysql &>/dev/null && echo "- MySQL client: $(mysql --version | awk '{print $3}')"
command -v psql &>/dev/null && echo "- PostgreSQL client: $(psql --version | awk '{print $3}')"
command -v redis-cli &>/dev/null && echo "- Redis CLI: $(redis-cli --version | awk '{print $2}')"
command -v sqlite3 &>/dev/null && echo "- SQLite: $(sqlite3 --version | awk '{print $1}')"

echo ""
echo "## Other"
echo ""
command -v ffmpeg &>/dev/null && echo "- ffmpeg: $(ffmpeg -version 2>&1 | head -1 | awk '{print $3}')"
command -v ssh &>/dev/null && echo "- SSH: $(ssh -V 2>&1 | awk '{print $1}' | cut -d'_' -f2 | tr -d ',')"
command -v curl &>/dev/null && echo "- curl: $(curl --version | head -1 | awk '{print $2}')"
command -v wget &>/dev/null && echo "- wget: $(wget --version | head -1 | awk '{print $3}')"
